version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: masterdetail_postgres
    environment:
      POSTGRES_PASSWORD: password
      DATABASE_URL: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "masteruser"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
